[package]
name = "day11"
version = "2020.12.11"
authors = ["Edward Waterman <edward.waterman@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
