[package]
name = "day02"
version = "2020.12.02"
authors = ["Edward Waterman <edward.waterman@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timed = "0.1.5"
"util" = { path = "../util" }
