[package]
name = "day16"
version = "0.1.0"
authors = ["Edward Waterman <edward.waterman@tum.de>"]
edition = "2018"

[dependencies]
regex = "1.4.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

